services:
    siriux_user.registration.form.type:
        class: Siriux\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: siriux_user_registration }

    siriux_user.profile.form.type:
        class: Siriux\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: siriux_user_profile }
